/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicDiagRouteImport } from './routes/api/public/diag'
import { Route as ApiPublicDlRouteImport } from './routes/api/public/dl'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiagRoute = ApiPublicDiagRouteImport.update({
  id: '/api/public/diag',
  path: '/api/public/diag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDlRoute = ApiPublicDlRouteImport.update({
  id: '/api/public/dl',
  path: '/api/public/dl',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/diag': typeof ApiPublicDiagRoute
  '/api/public/dl': typeof ApiPublicDlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/diag': typeof ApiPublicDiagRoute
  '/api/public/dl': typeof ApiPublicDlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/diag': typeof ApiPublicDiagRoute
  '/api/public/dl': typeof ApiPublicDlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/diag' | '/api/public/dl'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/diag' | '/api/public/dl'
  id: '__root__' | '/' | '/api/public/diag' | '/api/public/dl'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDiagRoute: typeof ApiPublicDiagRoute
  ApiPublicDlRoute: typeof ApiPublicDlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diag': {
      id: '/api/public/diag'
      path: '/api/public/diag'
      fullPath: '/api/public/diag'
      preLoaderRoute: typeof ApiPublicDiagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dl': {
      id: '/api/public/dl'
      path: '/api/public/dl'
      fullPath: '/api/public/dl'
      preLoaderRoute: typeof ApiPublicDlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDiagRoute: ApiPublicDiagRoute,
  ApiPublicDlRoute: ApiPublicDlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
